version: 2
jobs:
  build:
    working_directory: ~/repo
    docker:
        - image: dancinllama/dockerdx
    steps:
      - checkout
      - run:
          name: Run Lightning Web Component Unit Tests
          command: |
              npm install @salesforce/lwc-jest --save-dev
              npm run test:unit
