version: 2
jobs:
  build:
    docker:
      - image: dancinllama/dockerdx
    steps:
      - checkout # check out the code in the project directory
      - run: echo "Starting tests" # run the `echo` command
