version: 2

# Defining default values for all jobs
defaults: &defaults
  
jobs:
  build:
    working_directory: ~/repo
    docker:
        - image: dancinllama/dockerdx
    steps:
        - checkout
        - run:
            name: Install JEST
            command: |
              ls -la
              npm install @salesforce/lwc-jest --save-dev
              npm run test:unit
      - run:
          name: Run Lightning Web Component Unit Tests
          command: |
              npm run test:unit
